export const ALL_PLACES_REQUEST = 'ALL_PLACES_REQUEST'
export const ALL_PLACES_SUCCESS = 'ALL_PLACES_SUCCESS'
export const ALL_PLACES_FAIL = 'ALL_PLACES_FAIL'

export const PLACE_DETAILS_REQUEST = 'PLACE_DETAILS_REQUEST'
export const PLACE_DETAILS_SUCCESS = 'PLACE_DETAILS_SUCCESS'
export const PLACE_DETAILS_FAIL = 'PLACE_DETAILS_FAIL'

export const CREATE_PLACE_REQUEST = 'CREATE_PLACE_REQUEST';
export const CREATE_PLACE_SUCCESS = 'CREATE_PLACE_SUCCESS';
export const CREATE_PLACE_FAIL = 'CREATE_PLACE_FAIL';

export const UPDATE_PLACE_REQUEST = 'UPDATE_PLACE_REQUEST';
export const UPDATE_PLACE_SUCCESS = 'UPDATE_PLACE_SUCCESS';
export const UPDATE_PLACE_FAIL = 'UPDATE_PLACE_FAIL'

export const DELETE_PLACE_REQUEST = 'DELETE_PLACE_REQUEST';
export const DELETE_PLACE_SUCCESS = 'DELETE_PLACE_SUCCESS';
export const DELETE_PLACE_FAIL = 'DELETE_PLACE_FAIL';

export const CREATE_PLACE_REVIEW_REQUEST = 'CREATE_PLACE_REVIEW_REQUEST';
export const CREATE_PLACE_REVIEW_SUCCESS = 'CREATE_PLACE_REVIEW_SUCCESS';
export const CREATE_PLACE_REVIEW_FAIL = 'CREATE_PLACE_REVIEW_FAIL';

export const GET_PLACE_REVIEW_REQUEST = 'GET_PLACE_REVIEW_REQUEST'
export const GET_PLACE_REVIEW_SUCCESS = 'GET_PLACE_REVIEW_SUCCESS'
export const GET_PLACE_REVIEW_FAIL = 'GET_PLACE_REVIEW_FAIL'

export const UPDATE_PLACE_REVIEW_REQUEST = 'UPDATE_PLACE_REVIEW_REQUEST'
export const UPDATE_PLACE_REVIEW_SUCCESS = 'UPDATE_PLACE_REVIEW_SUCCESS'
export const UPDATE_PLACE_REVIEW_FAIL = 'UPDATE_PLACE_REVIEW_FAIL'

export const DELETE_PLACE_REVIEW_REQUEST = 'DELETE_PLACE_REVIEW_REQUEST'
export const DELETE_PLACE_REVIEW_SUCCESS = 'DELETE_PLACE_REVIEW_SUCCESS'
export const DELETE_PLACE_REVIEW_FAIL = 'DELETE_PLACE_REVIEW_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'