export const CREATE_STORY_REQUEST = 'CREATE_STORY_REQUEST';
export const CREATE_STORY_SUCCESS = 'CREATE_STORY_SUCCESS';
export const CREATE_STORY_FAIL = 'CREATE_STORY_FAIL';

export const GET_STORIES_REQUEST = 'GET_STORIES_REQUEST';
export const GET_STORIES_SUCCESS = 'GET_STORIES_SUCCESS';
export const GET_STORIES_FAIL = 'GET_STORIES_FAIL';

export const GET_STORY_DETAILS_REQUEST = 'GET_STORY_DETAILS_REQUEST';
export const GET_STORY_DETAILS_SUCCESS = 'GET_STORY_DETAILS_SUCCESS';
export const GET_STORY_DETAILS_FAIL = 'GET_STORY_DETAILS_FAIL';

export const UPDATE_STORY_REQUEST = 'UPDATE_STORY_REQUEST';
export const UPDATE_STORY_SUCCESS = 'UPDATE_STORY_SUCCESS';
export const UPDATE_STORY_FAIL = 'UPDATE_STORY_FAIL';

export const DELETE_STORY_REQUEST = 'DELETE_STORY_REQUEST';
export const DELETE_STORY_SUCCESS = 'DELETE_STORY_SUCCESS';
export const DELETE_STORY_FAIL = 'DELETE_STORY_FAIL';

export const COMMENT_STORY_REQUEST = 'COMMENT_STORY_REQUEST';
export const COMMENT_STORY_SUCCESS = 'COMMENT_STORY_SUCCESS';
export const COMMENT_STORY_FAIL = 'COMMENT_STORY_FAIL';

export const UPDATE_COMMENT_STORY_REQUEST = 'UPDATE_COMMENT_STORY_REQUEST';
export const UPDATE_COMMENT_STORY_SUCCESS = 'UPDATE_COMMENT_STORY_SUCCESS';
export const UPDATE_COMMENT_STORY_FAIL = 'UPDATE_COMMENT_STORY_FAIL';

export const DELETE_COMMENT_STORY_REQUEST = 'DELETE_COMMENT_STORY_REQUEST';
export const DELETE_COMMENT_STORY_SUCCESS = 'DELETE_COMMENT_STORY_SUCCESS';
export const DELETE_COMMENT_STORY_FAIL = 'DELETE_COMMENT_STORY_FAIL';

export const LIKE_STORY_REQUEST = 'LIKE_STORY_REQUEST'
export const LIKE_STORY_SUCCESS = 'LIKE_STORY_SUCCESS'
export const LIKE_STORY_FAIL = "LIKE_STORY_FAIL"

export const CLEAR_ERRORS = 'CLEAR_ERRORS'